# Enable Pointing & Mouse Engine
CONFIG_ZMK_POINTING=y
CONFIG_INPUT=y

# Expand Stack Memory for Complex Geometry & Inertial Calculations
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_MAIN_STACK_SIZE=2048

# Power Optimizations for BLE Battery Management
CONFIG_ZMK_SLEEP=y
CONFIG_PM_DEVICE=y
