manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: halfdane
      url-base: https://github.com/halfdane
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
    # This project contains include/dt-bindings/zmk/input_gestures.h
    - name: zmk-input-gestures
      remote: halfdane
      revision: main
    # Absolute mode Cirque driver fork
    - name: cirque-input-module
      remote: halfdane
      revision: main
  self:
    path: config